from typing import TypedDict, Annotated, List, Optional
import operator

class AgentState(TypedDict):
    query: str
    # sub_questions: The sub-tasks generated by the planner
    sub_questions: Annotated[List[str], operator.add]
    # retrieved_docs: Raw data from search tools
    retrieved_docs: Annotated[List[str], operator.add]
    # graded_docs: Filtered relevant documents
    graded_docs: Annotated[List[str], operator.add]
    
    needs_retry: bool
    # Use operator.add so retry_count increments automatically
    retry_count: Annotated[int, operator.add]
    
    final_report: str
    has_hallucination: bool
    fallback_triggered: bool